grid_map_topic: /grid_map_nav/grid_map
grid_map_visualizations:
  - name: elevation_points
    type: point_cloud
    params:
     layer: global_map_boundary
  - name: elevation_grid
    type: occupancy_grid
    params:
     layer: global_map_boundary
     data_min: 0
     data_max: 255
